version: '3'

services:
  mongodump:
    image: mongo:${MONGO_VERSION}
    env_file:
      - '.env'
    volumes:
      - ./backup:/backup
      - ./scripts:/scripts
    command: sh -c 'chmod +x /scripts/*.sh && /scripts/mongodump.sh'

  mongorestore:
    image: mongo:${MONGO_VERSION}
    env_file:
      - '.env'
    volumes:
      - ./backup:/backup
      - ./scripts:/scripts
    command: sh -c 'mongod & chmod +x /scripts/*.sh && /scripts/mongorestore.sh'

  mongodb:
    image: mongo:${MONGO_VERSION}
    env_file:
      - '.env'
    volumes:
      - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_RESTORE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_RESTORE_PASSWORD}
    ports:
      - 27018:27017
